// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.KycSpider.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents spider-specific information about check document
    /// </summary>
    public partial class SpiderDocumentInfo
    {
        /// <summary>
        /// Initializes a new instance of the SpiderDocumentInfo class.
        /// </summary>
        public SpiderDocumentInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpiderDocumentInfo class.
        /// </summary>
        public SpiderDocumentInfo(string customerId = default(string), string documentId = default(string), string currentCheckId = default(string), string previousCheckId = default(string), SpiderCheckResultDiff checkDiff = default(SpiderCheckResultDiff))
        {
            CustomerId = customerId;
            DocumentId = documentId;
            CurrentCheckId = currentCheckId;
            PreviousCheckId = previousCheckId;
            CheckDiff = checkDiff;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocumentId")]
        public string DocumentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CurrentCheckId")]
        public string CurrentCheckId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreviousCheckId")]
        public string PreviousCheckId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CheckDiff")]
        public SpiderCheckResultDiff CheckDiff { get; set; }

    }
}
