// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.KycSpider.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents difference between two check results
    /// </summary>
    public partial class SpiderCheckResultDiff
    {
        /// <summary>
        /// Initializes a new instance of the SpiderCheckResultDiff class.
        /// </summary>
        public SpiderCheckResultDiff()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpiderCheckResultDiff class.
        /// </summary>
        public SpiderCheckResultDiff(IList<SpiderProfile> removedProfiles = default(IList<SpiderProfile>), IList<SpiderProfile> addedProfiles = default(IList<SpiderProfile>), IList<SpiderProfilePair> changedProfiles = default(IList<SpiderProfilePair>))
        {
            RemovedProfiles = removedProfiles;
            AddedProfiles = addedProfiles;
            ChangedProfiles = changedProfiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RemovedProfiles")]
        public IList<SpiderProfile> RemovedProfiles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddedProfiles")]
        public IList<SpiderProfile> AddedProfiles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChangedProfiles")]
        public IList<SpiderProfilePair> ChangedProfiles { get; set; }

    }
}
