// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.KycSpider.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Container with two versions of spider profile
    /// </summary>
    public partial class SpiderProfilePair
    {
        /// <summary>
        /// Initializes a new instance of the SpiderProfilePair class.
        /// </summary>
        public SpiderProfilePair()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpiderProfilePair class.
        /// </summary>
        public SpiderProfilePair(SpiderProfile previous = default(SpiderProfile), SpiderProfile current = default(SpiderProfile))
        {
            Previous = previous;
            Current = current;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Previous")]
        public SpiderProfile Previous { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Current")]
        public SpiderProfile Current { get; set; }

    }
}
