// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.KycSpider.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents spider profile
    /// </summary>
    public partial class SpiderProfile
    {
        /// <summary>
        /// Initializes a new instance of the SpiderProfile class.
        /// </summary>
        public SpiderProfile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpiderProfile class.
        /// </summary>
        public SpiderProfile(string profileId = default(string), string fullName = default(string), IList<string> datesOfBirth = default(IList<string>), IList<string> citizenships = default(IList<string>), IList<string> residences = default(IList<string>), IList<string> matchingLegalCategories = default(IList<string>))
        {
            ProfileId = profileId;
            FullName = fullName;
            DatesOfBirth = datesOfBirth;
            Citizenships = citizenships;
            Residences = residences;
            MatchingLegalCategories = matchingLegalCategories;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProfileId")]
        public string ProfileId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DatesOfBirth")]
        public IList<string> DatesOfBirth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Citizenships")]
        public IList<string> Citizenships { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Residences")]
        public IList<string> Residences { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MatchingLegalCategories")]
        public IList<string> MatchingLegalCategories { get; set; }

    }
}
