// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.KycSpider.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Repesents information about customer which is checks regularly by Kyc Spider Service
    /// </summary>
    public partial class VerifiableCustomerInfo
    {
        /// <summary>
        /// Initializes a new instance of the VerifiableCustomerInfo class.
        /// </summary>
        public VerifiableCustomerInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VerifiableCustomerInfo class.
        /// </summary>
        public VerifiableCustomerInfo(bool isPepCheckRequired, bool isCrimeCheckRequired, bool isSanctionCheckRequired, string customerId = default(string), string latestSpiderCheckId = default(string))
        {
            CustomerId = customerId;
            LatestSpiderCheckId = latestSpiderCheckId;
            IsPepCheckRequired = isPepCheckRequired;
            IsCrimeCheckRequired = isCrimeCheckRequired;
            IsSanctionCheckRequired = isSanctionCheckRequired;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LatestSpiderCheckId")]
        public string LatestSpiderCheckId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsPepCheckRequired")]
        public bool IsPepCheckRequired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsCrimeCheckRequired")]
        public bool IsCrimeCheckRequired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsSanctionCheckRequired")]
        public bool IsSanctionCheckRequired { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
